"""
Run Task-1 ingest → clean → diagnose and write docs/task-1/DIAGNOSTIC-RESULTS.md.
Execute from repo root: python notebooks/run_diagnostics.py
Or from notebooks/: python run_diagnostics.py

For fast testing with a small sample (no large CSV / OOM):
  set USE_SAMPLE_DATA=1
  python notebooks/run_diagnostics.py
Uses data/sample/BrentOilPrices_sample.csv (generate via scripts/generate_sample_data.py).
"""

import os
import warnings
from pathlib import Path
from datetime import datetime
from typing import Any, cast

ROOT = Path(__file__).resolve().parent.parent
USE_SAMPLE_DATA = os.environ.get("USE_SAMPLE_DATA", "").strip().lower() in ("1", "true", "yes")
if USE_SAMPLE_DATA:
    RAW_DIR = ROOT / "data" / "sample"
    BRENT_CSV = "BrentOilPrices_sample.csv"
else:
    RAW_DIR = ROOT / "data" / "raw"
    BRENT_CSV = "BrentOilPrices.csv"
EVENTS_DIR = ROOT / "data" / "events"
PROCESSED_DIR = ROOT / "data" / "processed"
DOCS_TASK1 = ROOT / "docs" / "task-1"


def main():
    import pandas as pd
    from statsmodels.tsa.stattools import adfuller, kpss
    from statsmodels.tools.sm_exceptions import InterpolationWarning

    DOCS_TASK1.mkdir(parents=True, exist_ok=True)
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    # Ingest (match Task-1: strip columns, parse dates including mixed formats)
    df_brent = pd.read_csv(RAW_DIR / BRENT_CSV)
    df_brent.columns = [c.strip() for c in df_brent.columns]
    date_col = df_brent["Date"].astype(str).str.strip()
    try:
        df_brent["Date"] = pd.to_datetime(date_col, format="mixed")
    except TypeError:
        df_brent["Date"] = pd.to_datetime(date_col, errors="coerce")
    df_brent = (
        df_brent.dropna(subset=["Date", "Price"])
        .sort_values("Date")
        .rename(columns={"Price": "price"})
    )
    brent_ts = df_brent.set_index("Date")["price"].sort_index()
    brent_ts = brent_ts[~brent_ts.index.duplicated(keep="first")]
    brent_ts = cast(pd.Series, brent_ts)

    df_events = pd.read_csv(EVENTS_DIR / "geopolitical_economic_opec_events.csv")
    df_events["date"] = pd.to_datetime(df_events["date"])
    trading_days = cast(pd.DatetimeIndex, brent_ts.index)

    def first_trading_on_or_after(d: Any) -> pd.Timestamp | None:
        on_after = cast(pd.DatetimeIndex, trading_days[trading_days >= pd.Timestamp(d)])
        return on_after[0] if len(on_after) > 0 else None

    df_events["trading_date"] = df_events["date"].apply(first_trading_on_or_after)
    df_events = df_events.dropna(subset=["trading_date"])

    returns = cast(pd.Series, brent_ts.pct_change().dropna())

    # Diagnose: ADF and KPSS
    def run_adf(s, name):
        r = adfuller(s.dropna(), autolag="AIC")
        return {"series": name, "ADF_stat": r[0], "pvalue": r[1], "reject": r[1] < 0.05}

    def run_kpss(s, name):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=InterpolationWarning)
            r = kpss(s.dropna(), regression="c", nlags="auto")
        return {"series": name, "KPSS_stat": r[0], "pvalue": r[1], "reject": r[1] < 0.05}

    adf_l = run_adf(brent_ts, "Brent levels")
    adf_r = run_adf(returns, "Brent returns")
    kpss_l = run_kpss(brent_ts, "Brent levels")
    kpss_r = run_kpss(returns, "Brent returns")

    results_md = f"""# Task-1 Diagnostic Results

Generated by workflow script on {datetime.now().strftime("%Y-%m-%d %H:%M")}.
Same results are produced by `notebooks/task1_ingest_clean_diagnose.ipynb`.

## Data summary

- **Brent series**: {len(brent_ts):,} observations, {pd.Timestamp(cast(Any, brent_ts.index.min())).date()} to {pd.Timestamp(cast(Any, brent_ts.index.max())).date()}.
- **Returns**: {len(returns):,} observations.
- **Events**: {len(df_events)} events aligned to first trading day on or after calendar date.

## Stationarity (ADF and KPSS)

| Series | ADF stat | ADF p-value | Reject non-stationary (5%) | KPSS stat | KPSS p-value | Reject level stationary (5%) |
|--------|----------|-------------|----------------------------|-----------|--------------|------------------------------|
| Brent levels | {adf_l["ADF_stat"]:.4f} | {adf_l["pvalue"]:.4f} | {adf_l["reject"]} | {kpss_l["KPSS_stat"]:.4f} | {kpss_l["pvalue"]:.4f} | {kpss_l["reject"]} |
| Brent returns | {adf_r["ADF_stat"]:.4f} | {adf_r["pvalue"]:.4f} | {adf_r["reject"]} | {kpss_r["KPSS_stat"]:.4f} | {kpss_r["pvalue"]:.4f} | {kpss_r["reject"]} |

- **ADF**: H0 = unit root. Reject H0 at 5% ⇒ evidence of stationarity.
- **KPSS**: H0 = level stationary. Reject H0 at 5% ⇒ evidence of non-stationarity.

## Conclusions for modeling

1. **Levels**: Brent price levels are typically **non-stationary** (ADF does not reject unit root).
2. **Returns**: Brent **returns are treated as stationary** for change point modeling (ADF rejects unit root; KPSS does not reject level stationarity).
3. **Volatility**: Rolling volatility shows clear time variation (2008, 2020). **Volatility is time-varying**; Task-2 should consider heteroskedastic or regime-switching variance.
4. **Autocorrelation**: See ACF/PACF in the notebook; can guide AR/MA terms in future models.

## Figures

Run `notebooks/task1_ingest_clean_diagnose.ipynb` to generate:
- `diagnostic_trend_volatility.png`: Price levels and rolling volatility.
- `diagnostic_acf_pacf_returns.png`: ACF and PACF of returns.
"""

    (DOCS_TASK1 / "DIAGNOSTIC-RESULTS.md").write_text(results_md, encoding="utf-8")
    print("Written:", DOCS_TASK1 / "DIAGNOSTIC-RESULTS.md")

    # Save processed series
    brent_ts.to_csv(PROCESSED_DIR / "brent_prices_cleaned.csv", index=True)
    returns.to_csv(PROCESSED_DIR / "brent_returns.csv", index=True)
    df_events.to_csv(PROCESSED_DIR / "events_aligned.csv", index=False)
    print("Processed outputs saved to", PROCESSED_DIR)


if __name__ == "__main__":
    main()
